### ISSUE TITLE
Rework eslint. 

### ISSUE THREAD

**Issue by iberdinsky-skilld** [skilld-labs/kaizen#2]
Rework .eslintrc to extend core rules.

**Comment by andypost** [comment]
https://www.drupal.org/node/2873849 change record
and guide https://www.drupal.org/docs/develop/standards/javascript/eslint-settings

**Comment by andypost** [comment]
Yes, it must https://www.drupal.org/node/2986680

**Comment by koskinpark** [comment]
Main thing to clarify: should we extend eslintrc from core? For now theme eslint was copypasted from core & edited. If yes - means until local site isn't deployed - we can't run `gulp lint`, since no core folder.
2nd thing to clarify: if we gonna extend eslint from core, how we can override settings there? For now - can't answer (https://www.npmjs.com/package/gulp-eslint)

**Comment by koskinpark** [comment]
Maybe makes sense to use Drupal 8.6 way to lint theme js?
https://www.drupal.org/list-changes/drupal/published?keywords_description=Eslint
https://www.npmjs.com/package/gulp-prettier
